sudo: required
language: rust
rust:
  - stable

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email: false

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
      - libssl-dev

before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    export PATH=$HOME/.cargo/bin:$PATH
    cargo install cargo-tarpaulin || echo "cargo-tarpaulin already installed"
    cargo install-update -a # update outdated cached binaries
  fi

script:
  - cargo build
  - cargo test

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    # measure code coverage and upload to coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

notifications:
  email: false
  slack: imdea-software:fdyPmym7oicfvSQTL5zy21n3
