sudo: required
language: rust
rust:
  - stable

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email: false

cache:
  cargo: true
  apt: true

addons:
  apt:
      packages:
          - libssl-dev

before_cache: |
	if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
  - cargo build
  - cargo test

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

notifications:
  email: false
  slack: imdea-software:fdyPmym7oicfvSQTL5zy21n3
