[package]
name = "planet_sim"
version = "0.1.0"
edition = "2018"

authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]
license = "MIT/Apache-2.0"

default-run = "run"

[dependencies]
threshold = "0.6.3"
rand = "0.7"
permutator = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2"
rayon = "1.2.0"
futures = "0.3.1"
bytes = "0.5.3"
tokio = { version = "0.2.8", features = ["full"] }
tokio-util = { version = "0.2.0", features = ["codec"] }
clap = "2.33.0"


[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.8"

