[package]
name = "fantoch"
version = "0.1.0"
edition = "2018"

authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]
license = "MIT/Apache-2.0"

[features]
timing = ["fantoch_timing"]

[dependencies]
ahash = "0.3.4"
bincode = "1.2.1"
bytes = "0.5.4"
futures = { version = "0.3.5", features = ["alloc"] }
parking_lot = "0.10.2"
rand = "0.7.3"
serde = { version = "1.0.110", features = ["derive"] }
threshold = "0.8.7"
tokio = { version = "0.2.21", features = ["full", "parking_lot"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
tracing = "0.1.14"

fantoch_timing = { path = "../fantoch_timing", optional = true }

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
