[package]
name = "fantoch_mc"
version = "0.1.0"
edition = "2021"

authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
stateright = "0.20.0"

fantoch = { path = "../fantoch", default-features = false }
