[package]
name = "fantoch_exp"
version = "0.1.0"
edition = "2018"

authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
color-eyre = "0.3.2"
futures = "0.3.5"
rusoto_core = "0.44.0"
rusoto_ec2 = "0.44.0"
tracing = "0.1.14"
tracing-futures = "0.2.4"
tokio = { version = "0.2.21", features = [ "time" ]}
tracing-subscriber = "0.2.5"
tsunami = { git = "https://github.com/vitorenesduarte/tsunami", rev = "504aecab35c01c6419d9be65a462b7d19c65cf65", features = [ "aws", "baremetal" ] }
