[package]
name = "fantoch_exp"
version = "0.1.0"
edition = "2018"

authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
color-eyre = "0.3.4"
eyre = "0.4.3"
futures = { version = "0.3.5", features = [] }
openssh = "0.6.2"
rusoto_core = "0.44.0"
rusoto_credential = "0.44.0"
rusoto_ec2 = "0.44.0"
tracing = "0.1.14"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.5"
tokio = { version = "0.2.21", features = [ "time" ]}
tsunami = { git = "https://github.com/vitorenesduarte/tsunami", rev = "1a4b5bc4b5d95c3770c01761579e0ba8d0d051c5", features = [ "aws" ] }

fantoch = { path = "../fantoch" }
