[package]
name = "fantoch_plot"
version = "0.1.0"
edition = "2018"

authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
pyo3 = "0.11.0"
color-eyre = "0.4.1"

fantoch = { path = "../fantoch" }
fantoch_exp = { path = "../fantoch_exp", default-features = false }
